### PR TITLE
Added Sponsor Section Component 

### LINKED ISSUE #29: Adding Sponsors Section Component

### PR DESCRIPTION
**Pull request by Palaksharma23**
Fixes #29

### CODE REVIEW

**Review by Janvi-Thakkar — COMMENTED** [review]
@Palaksharma23, I feel this component is too specific. No other UI library provides this. Still if all think this as a component to be added in the library, I would request you to do suggested changes.

**Review by Janvi-Thakkar — COMMENTED** [review]
As we are going to use storybook as a docs about implementation, please add different stories for different values of variables.

**Comment by Palaksharma23** [comment]
> @Palaksharma23, I feel this component is too specific. No other UI library provides this. Still if all think this as a component to be added in the library, I would request you to do suggested changes.

We should be adding this component in the UI Library as the main aim of the project is to reduce UI development time and maintain consistency, After the basic components are done we can provide more components as well to serve the purpose. Also, I have mentioned this component in the proposal as well.

**Review by YashKandalkar — APPROVED** [review]
LGTM! @Palaksharma23 nice work! :rocket:

**Review by HarshCasper — APPROVED** [review]

**Pull request merged**
