### PR TITLE
Added Card component

### PR DESCRIPTION
**Pull request by Janvi-Thakkar**
image
image

### CODE REVIEW

**Comment by Palaksharma23** [comment]
Nice work! @Janvi-Thakkar 🚀

Here are a few things to work upon

The designing of cards is very simple right now, can you design them according to the Figma file I have shared with you. https://www.figma.com/file/QBccI5A8ATyV5L3dDe0KmY/Components?node-id=232%3A192 Those 5 designs are sufficient for the needs.  

Also, try to maintain the nature of the cards like in the Normal section under cards the design you are trying to achieve is the square card I suppose. But when I increase the amount of text in the paragraph the design gets changed and looks similar to that of the styling section under cards. 

This is your intended square design
image
  
This is the effect I get on increasing the text inside the card
image

**Comment by Janvi-Thakkar** [comment]
> Nice work! @Janvi-Thakkar 🚀
> 
> Here are a few things to work upon
> 
> The designing of cards is very simple right now, can you design them according to the Figma file I have shared with you. https://www.figma.com/file/QBccI5A8ATyV5L3dDe0KmY/Components?node-id=232%3A192 Those 5 designs are sufficient for the needs.
> 
> Also, try to maintain the nature of the cards like in the Normal section under cards the design you are trying to achieve is the square card I suppose. But when I increase the amount of text in the paragraph the design gets changed and looks similar to that of the styling section under cards.
> 
> This is your intended square design image
> 
> This is the effect I get on increasing the text inside the card image

@Palaksharma23 Thank you for the review and for giving valuable feedback. Below are some points which might clear the picture.

1. The elements inside the card are adjustable by users so we would be just providing an outer layout and everything inside would be as per the user's convenience so there can be hundred different use cases for this single outer layout.

2. Here class styling, functional styling, and styling refer to show that the user can modify the cards by providing classes or style objects or by returning style objects from the function for dynamic styling.

3. outer width will be fully customizable as per the user's need to expand it. so adding more content would expand the card. and again it can be controlled by custom styling or based on outer division.

please let me know if anything is still needed to be modified.

**Review by YashKandalkar — APPROVED** [review]
LGTM! :rocket: 
Good work!

**Comment by Palaksharma23** [comment]
> > image
> 
> @Palaksharma23 Thank you for the review and for giving valuable feedback. Below are some points which might clear the picture.
> 
> 1. The elements inside the card are adjustable by users so we would be just providing an outer layout and everything inside would be as per the user's convenience so there can be hundred different use cases for this single outer layout.
> 2. Here class styling, functional styling, and styling refer to show that the user can modify the cards by providing classes or style objects or by returning style objects from the function for dynamic styling.
> 3. outer width will be fully customizable as per the user's need to expand it. so adding more content would expand the card. and again it can be controlled by custom styling or based on outer division.

oh Got it! 
Nice work! @Janvi-Thakkar ❤

**Pull request merged**
