### PR TITLE
Added Toggle Component

### PR DESCRIPTION
**Pull request by Palaksharma23**

### CODE REVIEW

**Review by YashKandalkar — APPROVED** [review]
LGTM! @Palaksharma23 nice work! :rocket:

**Review by Janvi-Thakkar — COMMENTED** [review]
@Palaksharma23 LGTM except the colors you used. maybe by mistake, you have 2 different colors for primary round and primary sqare has different colors. same goes for secondary buttons. Also, dark color code is different than what we have used else where. Please have a look at these things. correct me if I am wrong:)

**Comment by Palaksharma23** [comment]
@Janvi-Thakkar, I have added a function to emit the value of toggle button, can you please once re-review it :)

**Review by Janvi-Thakkar — APPROVED** [review]
@Palaksharma23 LGTM:)

**Pull request merged**
