### PR TITLE
Created the readme along with instr to get started 

### LINKED ISSUE #43: Need of updated README.md
Currently, there is nothing in Readme, which needs to be updated with the necessary details!

### PR DESCRIPTION
**Pull request by legendarykamal**
Signed-off-by: Kamal Nayan <geniusamansingh@gmail.com>

This PR fixes #43 

Created the readme along with instructions on how to get started.

### CODE REVIEW

**Comment by legendarykamal** [comment]
@Palaksharma23 please review .

**Comment by Palaksharma23** [comment]
Work on README is in progress in this pull request https://github.com/moja-global/ui-library/pull/44 @legendarykamal

**Comment by legendarykamal** [comment]
ahh I missed it sry @Palaksharma23 any idea why are we taking so longg  to even merge simple README files ?

**Comment by HarshCasper** [comment]
> ahh I missed it sry @Palaksharma23 any idea why are we taking so longg to even merge simple README files ?

FYI: READMEs are not simple

**Comment by legendarykamal** [comment]
@HarshCasper not as much as long lines of code and provided they help other contributors get to know about the project better.

**Pull request closed without merging**
