### PR TITLE
Added Range-Slider Component

### LINKED ISSUE #9: Adding Slider Component Folder in the ui library

### PR DESCRIPTION
**Pull request by Palaksharma23**
Fixes #9

### CODE REVIEW

**Review by Janvi-Thakkar — COMMENTED** [review]
@Palaksharma23, secondary slider should also have two different colors for filled and un-filled parts of slider. also add border-radius to secondary slider

**Review by YashKandalkar — APPROVED** [review]
LGTM! :rocket: 
(Have a look at @Janvi-Thakkar's comment)

**Comment by Palaksharma23** [comment]
Yes, @Janvi-Thakkar @YashKandalkar Before making the pull request, I tried to implement the different colors for filled and unfilled parts of the slider but I was unable to do that. If you have idea on how to do that you can suggest :)

**Comment by Janvi-Thakkar** [comment]
> Yes, @Janvi-Thakkar @YashKandalkar Before making the pull request, I tried to implement the different colors for filled and unfilled parts of the slider but I was unable to do that. If you have idea on how to do that you can suggest :)

I have sent related things to you.

**Comment by Janvi-Thakkar** [comment]
Great work @Palaksharma23, just few small changes, and this will be good to go:)
- **outerColor** and **innerColor** look confusing, can we have something like **barColor** and **activeBarColor**?
- For the secondary slider is there any option to provide the color for that rounded slider handle as a prop?
- **primary slider** is not having cursor: pointer please add that!

**Comment by Palaksharma23** [comment]
> Great work @Palaksharma23, just few small changes, and this will be good to go:)
> 
> * **outerColor** and **innerColor** look confusing, can we have something like **barColor** and **activeBarColor**?
> * For the secondary slider is there any option to provide the color for that rounded slider handle as a prop?
> * **primary slider** is not having cursor: pointer please add that!

I have changed the props name accordingly
Yes, we can provide the color for the rounded slider handle as a prop :)

**Review by Janvi-Thakkar — APPROVED** [review]
Great @Palaksharma23 :)
I can see the changes in vue file but maybe you have not changed those variables in storybook! please do it and this PR can be merged once done 🚀

**Pull request merged**
